apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ghost-prod

resources:
  - ../../base

patchesStrategicMerge:
  - prod-values.yaml

commonLabels:
  environment: production
