apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ghost

resources:
  - mysql-deployment.yaml
  - ghost-deployment.yaml
  - ghost-service.yaml
  - ghost-ingress.yaml
  - ghost-sealed-secrets.yaml

commonLabels:
  app.kubernetes.io/name: ghost
  app.kubernetes.io/instance: ghost
  app.kubernetes.io/managed-by: argocd
