apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ghost

resources:
  - argocd-application.yaml
  - ghost-sealed-secrets.yaml

commonLabels:
  app.kubernetes.io/name: ghost
  app.kubernetes.io/instance: ghost
  app.kubernetes.io/managed-by: argocd
